color: green
fieldLayouts:
  dcb0d2cc-6347-4f01-a98e-89c2880f36f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-07T07:44:18+00:00'
            elementCondition: null
            fieldUid: 325bc40a-f910-4f02-8513-ae0deb46331a # Heading Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9de9916b-68a7-4dcf-b532-53aa2f0ec41e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T07:44:18+00:00'
            elementCondition: null
            fieldUid: 39144c82-559e-40ce-acee-f48619b47d6d # Icon Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0e7c6a0-d6c6-4926-9958-3376b381c3b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-07T07:44:18+00:00'
            elementCondition: null
            fieldUid: 61b09cc2-d26f-4979-b3b6-604f9c667feb # Tab Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3279086-f0c2-4374-8f27-7e36b3f66b0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aea0157a-1ab4-4f87-b044-4dea6c1feaec
        userCondition: null
handle: aboutSystemSection
hasTitleField: false
icon: align-justify
name: 'About System Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
