color: null
fieldLayouts:
  edd20605-3720-41b5-bab5-2109d257f53d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-06T19:27:27+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Company Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eb7e992-98a2-42f2-a4cc-c21a674be9fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-06T19:27:27+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Company Text
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a1b136a-15a3-408c-811d-f3265e7d7755
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-06T19:27:27+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b51ee180-2fce-456d-9198-71da8392549d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e35b69c-a276-4df2-9aac-c25ed366280b
        userCondition: null
handle: companyGoals
hasTitleField: false
icon: null
name: 'Company Goals'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
