color: null
fieldLayouts:
  0095c222-ff5d-4134-aa93-6e51285d5ca7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T05:09:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69d7d8c6-b263-4c91-bb4b-5a5d8f3c8bfc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: 9cecf014-0859-4c02-88fc-2f12bda2e735 # FAQ - Question
            handle: question
            includeInCards: false
            instructions: null
            label: Question
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81ee4c2b-49aa-47a0-8317-8274119f5b7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: 2e482ae0-dadb-4ec6-800a-74b02b393492 # FAQ - Answer
            handle: answer
            includeInCards: false
            instructions: null
            label: Answer
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 423a5759-35da-445d-8a1b-21719e3d525c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5632118a-ae3e-4fac-a0b5-961061bf64c5
        userCondition: null
handle: faq
hasTitleField: false
icon: question
name: FAQ
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{question}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
