color: sky
fieldLayouts:
  c47b2c80-5bb4-49a0-86cd-7a5f99f7e0c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-09T09:26:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e7f01241-5568-4b8d-9ae7-693213ebdc89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: 67f3a8e1-fb07-4135-9632-b9d51eb53605 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c687ca4-4975-4480-9bd5-d627e456a684
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce86d34f-8383-493c-8d16-30f443f6a91b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: f0337310-b49a-4d17-bfa5-a60cbea3c0b3 # Fleet Entries
            handle: fleet
            includeInCards: false
            instructions: null
            label: Fleet
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88e96031-c4d7-448b-94bc-6078cf3da129
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4835d56-b0d5-4c3f-bff3-9db36ba9d9d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1671516a-584d-44f1-a06e-487e38689b0f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: 4ddfdf96-b71c-4a70-826e-4b46188161a3 # Theme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5684bbc3-5b04-402c-bac3-a4583b40b392
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-09T09:26:20+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d443e55-7805-4113-9d37-eec4cc01f330
            userCondition: null
            warning: null
            width: 50
        name: 'Block Settings'
        uid: aad23b3c-e0dc-4d26-a8d6-e1a18cce7bca
        userCondition: null
handle: fleetSlider
hasTitleField: false
icon: van-shuttle
name: 'Fleet Slider'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
