color: cyan
fieldLayouts:
  42b24353-ca4e-4a67-aaad-2832dcc75cc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:00:05+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6bbe991-f5a1-4f82-8f59-8ed6407cbfac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-21T09:00:05+00:00'
            elementCondition: null
            fieldUid: 86b0adf0-5bb4-4cc3-b597-b32bd746081e # Rich Text - Full
            handle: paragraph
            includeInCards: false
            instructions: null
            label: Paragraph
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c118cfc2-9056-42e8-9dc8-7eaca6b033ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f116abc-df2d-49ad-94a1-e2be9bf1773b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-21T09:03:49+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe7b41e0-9f58-452f-8c5f-c998019a2780
            userCondition: null
            warning: null
            width: 100
        name: 'Block Setting'
        uid: 244d5c54-4e16-48e4-8f3f-f5e1d1767de8
        userCondition: null
handle: headingParagraph
hasTitleField: false
icon: badge-check
name: 'Heading + Paragraph'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
