color: purple
fieldLayouts:
  cd8f8b6e-bd02-4120-abb3-644a86e13d14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T05:09:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: de0286a7-8a23-486b-8873-5c93e97ee355
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: 6e423f8b-75dd-4936-9837-37c0a49402b6 # Slider Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 982fd155-0edd-4ef2-acbc-cd9793702399
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5874f42b-81bb-4ac0-837b-9fc3b52474f1
            userCondition: null
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Leave blank to use the CTA content set in globals.'
            type: craft\fieldlayoutelements\Tip
            uid: cbd9008e-d72b-43ae-a8c7-c72ec91a766c
            userCondition: null
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Plain Text
            handle: ctaText
            includeInCards: false
            instructions: null
            label: 'CTA Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25994000-4c69-4d49-854c-ebf857c5467a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: ctaButton
            includeInCards: false
            instructions: null
            label: 'CTA Button'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8619b471-a8ad-4bea-a0bd-96986cd35316
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0fc5f68-2e89-4e70-b2fa-91b9171e9475
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96bb56db-baa1-4239-a0af-71b2d9e656dc
            userCondition: null
            warning: null
            width: 100
        name: 'Block Settings'
        uid: 31ad68c5-bf96-4fb8-bd4d-738e6d357d15
        userCondition: null
handle: imageSlider
hasTitleField: false
icon: images
name: 'Image Slider'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
