color: orange
fieldLayouts:
  01b5cae3-4961-4314-b0a4-53f4feafef6c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T10:30:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9726873e-ad84-4501-af7b-8dbbdeec5fb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T10:30:36+00:00'
            elementCondition: null
            fieldUid: 735cd1c0-1a58-4cc8-b37e-7275a35e8886 # Image Row Images
            handle: images
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a54ae4c-82c2-4582-8175-7f7522f7c451
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T10:30:36+00:00'
            elementCondition: null
            fieldUid: f9b7d774-c1a4-494c-963f-a5710417d6c8 # Aspect Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7958252c-5e13-4f96-a5ae-9eb570d66e78
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2642d382-49b9-46f0-8185-7e992510345d
        userCondition: null
handle: imageRow
hasTitleField: false
icon: image
name: 'Image Row'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
