color: yellow
fieldLayouts:
  f5d1ea38-d1f5-4f09-b0d4-12db5950fcd0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-04T07:48:43+00:00'
            elementCondition: null
            fieldUid: 4060ca93-4d55-48ba-be72-11fd85105282 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80a1645c-1ac0-4572-bf74-f6f8ee9cb8a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:28:34+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 687cc19b-7361-459d-9c9f-167bb3936993
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:28:34+00:00'
            elementCondition: null
            fieldUid: 86b0adf0-5bb4-4cc3-b597-b32bd746081e # Rich Text - Full
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10c4a8eb-8e29-458e-9e24-c0a5584fa3b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:28:34+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e95a7eb8-0cb8-449f-acf3-84b94587d6d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:48:43+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Company Text
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab4a12a4-94c4-4dd9-82c7-58f0964180a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-06T22:18:41+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Company Text
            handle: buttonColor
            includeInCards: false
            instructions: null
            label: 'Button Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66ad2d5a-46d9-4d44-a58a-4963f4ddabf0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e800a3a-9c08-4503-b518-eaf887d5edce
        userCondition: null
handle: keyAdvantage
hasTitleField: false
icon: key
name: 'Key advantage'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
