color: lime
fieldLayouts:
  09575a7c-913f-4675-a5a2-cccbc8206cb2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-04T07:31:25+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82fa5995-2a99-4769-b7c1-3db14b107764
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:31:25+00:00'
            elementCondition: null
            fieldUid: 86b0adf0-5bb4-4cc3-b597-b32bd746081e # Rich Text - Full
            handle: paragraph
            includeInCards: false
            instructions: null
            label: Paragraph
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd2ed204-ee6a-49e5-8dda-cf474109c0ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T07:31:25+00:00'
            elementCondition: null
            fieldUid: dfe774e8-bcfa-412e-b409-e0a511e36bca # Key Steps
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6004af87-02c7-4257-8500-4efc6c421382
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a032c9e4-ba3b-4afd-bc2c-1e09622f9f85
        userCondition: null
handle: keySteps
hasTitleField: false
icon: a
name: 'Key Steps'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
