color: null
fieldLayouts:
  1db74b2c-d45f-4a5e-82d6-7e31943a7f67:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-07T06:03:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e62e657-7216-4517-9039-b0a895986523
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-07T06:07:08+00:00'
            elementCondition: null
            fieldUid: e47e78ea-7cd0-4cc6-988b-f68b3801cd66 # Entry Title
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41f12b50-f365-4938-a9c5-872164dee098
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ae5911b-3e87-47d5-8218-cdebe40932bd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-07T06:07:08+00:00'
            elementCondition: null
            fieldUid: 787967f0-9a61-4502-9ec1-b413d02b9279 # Meta & Social Data
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5157dfe2-2102-4ec7-bb4d-61e65681fdbe
            userCondition: null
            warning: null
            width: 100
        name: 'Meta & Social Data'
        uid: ec05b914-6d52-43d1-a97d-8bda3ba7ff49
        userCondition: null
handle: pageBlogExterior
hasTitleField: true
icon: null
name: 'Page - Blog Exterior'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
