color: null
fieldLayouts:
  34605fbb-646d-4a84-8349-3abeb5dd5849:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T09:49:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 88232706-ee26-4b14-bd60-781d2f966a6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T09:51:46+00:00'
            elementCondition: null
            fieldUid: f2c22533-32b6-4c64-afdf-1ecd17a508fa # Quote Progress Title
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70037169-5767-4282-95f7-59e795c94f86
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T09:51:46+00:00'
            elementCondition: null
            fieldUid: 2e9c6a7b-2f62-436b-a6d8-004629a97ade # Quote Progress Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b08f53-54c6-477a-9a6a-3ead3f2bc88e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 71a064d3-bdc6-4a76-beb4-d6957208451b
        userCondition: null
handle: quoteProgress
hasTitleField: false
icon: list-check
name: 'Quote Progress'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
