color: rose
fieldLayouts:
  aef556dd-6f02-49d0-be32-8303bccc5432:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-06T05:09:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24732147-4d4a-4be8-998f-3329fb9d86f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: 491c947f-f0c2-4cd5-8908-c5f5eb7ac781 # Scrolling Text
            handle: null
            includeInCards: false
            instructions: 'Leave this blank to use the content set in **Globals**.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7ce69f2-1eef-425f-ba19-b2a491cb013a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62117d2e-1e90-49ea-8193-2892b48332ae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-06T05:09:00+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a45dcd2-566d-40d8-9895-fb3944a30ed1
            userCondition: null
            warning: null
            width: 100
        name: 'Block Settings'
        uid: f7b19021-2b52-4af9-ae5c-46838b480455
        userCondition: null
handle: scrollingText
hasTitleField: false
icon: font-case
name: 'Scrolling Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
