color: emerald
fieldLayouts:
  ff12628c-d109-4b3a-af61-160f4ae63def:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-09T09:00:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b26827c8-609b-49df-81e3-822f40d8c0f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:00:34+00:00'
            elementCondition: null
            fieldUid: fc1bbb5a-6159-44dc-955f-ed71bdc2ca73 # Icon Picker
            handle: icon
            includeInCards: false
            instructions: 'Select an icon from the picker.'
            label: Icon
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60658e10-9a05-4cea-8f29-2d7b9725ab97
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-09T09:03:04+00:00'
            elementCondition: null
            fieldUid: 53c480df-d338-438c-b3ef-bbcc64cef008 # Text Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5bdf65d-0a0d-4031-84a4-2e8e6f28cd21
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-09T09:00:34+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Plain Text
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e7c588b-3ffe-43cf-a240-391fb8adad2a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-09T09:00:34+00:00'
            elementCondition: null
            fieldUid: dee0e12a-d0be-4dce-864e-96f853d767f2 # Plain Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d4e5846-16b5-4f7a-b3df-13bcd1902015
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77a8e2bf-c84e-46ef-8bc2-75274609e56e
        userCondition: null
handle: textIconCard
hasTitleField: false
icon: icons
name: 'Text + Icon Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
