columnSuffix: null
handle: aspectRatio
instructions: null
name: 'Aspect Ratio'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
