columnSuffix: null
handle: brandIcon
instructions: null
name: 'Brand Icon'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Facebook
        -
          - value
          - facebook
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pinterest
        -
          - value
          - pinterest
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - TikTok
        -
          - value
          - tiktok
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - X
        -
          - value
          - x-twitter
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
