columnSuffix: null
handle: heroBackground
instructions: null
name: 'Hero Background'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - dark
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - medium
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
