columnSuffix: null
handle: iconHeadingDescription
instructions: null
name: 'Icon + Heading + Description'
searchable: false
settings:
  createButtonLabel: 'New card'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - dba48540-4a8f-4b66-a3b7-7e65a0c35e9b # Icon cards
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
