columnSuffix: null
handle: iconPicker
instructions: null
name: 'Icon Picker'
searchable: false
settings:
  iconSets: '*'
  renderId: null
  showLabels: true
translationKeyFormat: null
translationMethod: none
type: verbb\iconpicker\fields\IconPickerField
