columnSuffix: null
handle: servicesImageText
instructions: 'Text displayed over image on services block.'
name: 'Services Image Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 460
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
