columnSuffix: null
handle: socialLinks
instructions: null
name: 'Social Links'
searchable: false
settings:
  createButtonLabel: 'Add social link'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2ec883fa-306f-43aa-9106-cff3e6d1af50 # Social Links
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
