columnSuffix: null
handle: starRating
instructions: null
name: 'Star Rating'
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: 5
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  step: null
  suffix: stars
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
