columnSuffix: null
handle: textExcerpt
instructions: null
name: 'Text Excerpt'
searchable: false
settings:
  byteLimit: null
  charLimit: 185
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
